version: '3.8'
services:
  jupyter:
    container_name: HUB
    restart: on-failure:3
    hostname: juputerhub.test.local
    build:
      context:  ./jupyterhub_CUDA/
      dockerfile: Dockerfile
    ports:
      - 8900:8000
      - 8922:8022
    volumes:
      - fs:/home
      - sssdconf:/conf
    environment:
      - DEBUG=0
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: [utility, compute, video]
volumes:
  fs:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.1,rw,local_lock=all,noatime,rdma,port=20049"
      device: ":/fs"
  sssdconf:
    driver_opts:
      type: none
      device: "./conf"
      o: bind